### PR TITLE
fixed best score bug

### PR DESCRIPTION
**Pull request by astriskit**
> using session-storage
> will keep track of the session-storage until the tab is closed
> addressed #7

### CODE REVIEW

**Comment by PalashBansal** [comment]
Thanks for the fix, I will test and take decision accordingly.

**Comment by PalashBansal** [comment]
@astriskit 
I fetched changes but couldn't see score being saved, nor does it reflect in UI. Can you please look into once and help me in testing it.
image

**Comment by astriskit** [comment]
@PalashBansal - try this: 
> Play once. Note the "current score".
> Play again and notice that once you cross your last "current score", it will start updating.
> Will add necessary code next.
> If there is any other relevant observation, you found, let me know.

Basically, the state is not being reflected correctly in view.

 I won't be able to change anything in this PR - since the forked repo now stands deleted! Hence will remove this PR, but would send another PR referencing the same issue.

**Comment by astriskit** [comment]
Continue to - #38

**Comment by astriskit** [comment]
Continue to - #38

**Pull request closed without merging**
