### PR TITLE
best-score fixed - 2

### PR DESCRIPTION
**Pull request by astriskit**
- `Game.js` is prettified in the very first commit - so no changes there.
- After it changes to fix the bug.
- Addressing #7 and in continuation to #37

### CODE REVIEW

**Comment by astriskit** [comment]
@PalashBansal Check for the live version here - https://otv9o.csb.app/index.htm

**Comment by PalashBansal** [comment]
Thanks @astriskit  for the hard work, and thanks for https://otv9o.csb.app/index.htm helping in testing. Your fix works really great, but can you please remove the commit "prettified Game.js" 0b85ecc0690ff35e659655880c259805b1425559 out of PR as keeping all function arguments in individual line makes file unnecessarily big to scroll. 
However, other 3 commits are perfect and good to be merged in main repo.

Please let me know if you are facing difficulty in removing specific commit and I will find a way.

**Comment by astriskit** [comment]
@PalashBansal - the prettification usually adds to the longevity of the project and is considered as a good coding-practise; I'd suggest you to let it remain and include the prettier as a standard formatter. 

But, let me know, if you still want it removed. 

To know more about the prettier - https://prettier.io/

**Comment by PalashBansal** [comment]
Ok @astriskit I am merging this fix with refactored code. But will probably make some modifications on top of it in near future, especially the function arguments, again bringing to same line. Kinda using half of _prettier_

**Comment by astriskit** [comment]
@PalashBansal cool.

**Pull request merged**
